# conda env create --file environment.yml
# conda activate {{ cookiecutter.project_slug }}

name: {{ cookiecutter.project_slug }}
channels: 
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - ipykernel=6.17.0
  - matplotlib=3.6.0
  {% if cookiecutter.project_packages == "All" -%}
  - google-auth=2.14.0
  {% endif -%}
  - pandas=1.5.1
  - openpyxl=3.0.10
  {% if cookiecutter.project_packages == "All" -%}
  - pandas-gbq=0.17.9
  - scikit-learn=1.1.3
  - psycopg2=2.9.4
  - seaborn=0.12.1
  - mysql-connector-python=8.0.31
  {% endif -%} 